# Generated by Django 6.0 on 2025-12-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('hall_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.TextField()),
                ('rent', models.IntegerField(default=0)),
                ('additional_charges', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True)),
                ('receipt_no', models.CharField(max_length=50)),
                ('receipt_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
